[versions]
kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
logback = "1.5.19"
kaml = "0.102.0"
adventure = "4.25.0"
mcprotocollib = "1.21.4-SNAPSHOT"
netty = "4.1.97.Final"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
application = { id = "application" }

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
mcprotocollib-protocol = { module = "org.geysermc.mcprotocollib:protocol", version.ref = "mcprotocollib" }