#!/bin/bash

SERVER_DIR="test_server"
mkdir -p "$SERVER_DIR"
cd "$SERVER_DIR" || exit

echo "Downloading Minecraft server jar..."
wget -O server.jar https://piston-data.mojang.com/v1/objects/05e4b48fbc01f0385adb74bcff9751d34552486c/server.jar

echo "Agreeing to the EULA..."
echo "eula=true" > eula.txt

echo "Configuring server.properties for offline mode..."
cat <<EOL > server.properties
#Minecraft server properties
#Generated by mcserverinfo test_server script
online-mode=false
level-name=world
gamemode=creative
difficulty=easy
max-players=20
EOL

echo "Starting the Minecraft server..."
java -Xmx1024M -Xms1024M -jar server.jar nogui